import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const tracks = [
  {
    title: 'Morning Breeze',
    artist: 'yASu',
    genre: 'アンビエント',
    bpm: 80,
    duration: 180,
    price: 550,
    coverUrl: 'https://picsum.photos/seed/track1/400/400',
    previewUrl: '/audio/preview-1.mp3',
    fullUrl: '/audio/full-1.mp3',
    description: '朝の静けさをイメージした穏やかなアンビエント曲。ヨガや瞑想、朝のルーティン動画のBGMに最適。',
    tags: JSON.stringify(['リラックス', '瞑想', '朝', 'ヨガ']),
    mood: 'Calm',
    musicKey: 'C major',
  },
  {
    title: 'City Lights',
    artist: 'yASu',
    genre: 'エレクトロニカ',
    bpm: 128,
    duration: 210,
    price: 880,
    coverUrl: 'https://picsum.photos/seed/track2/400/400',
    previewUrl: '/audio/preview-2.mp3',
    fullUrl: '/audio/full-2.mp3',
    description: '都会の夜をテーマにしたアップテンポなエレクトロニカ。プロモーション動画やファッション映像に。',
    tags: JSON.stringify(['都市', '夜', 'エネルギッシュ', 'モダン']),
    mood: 'Energetic',
    musicKey: 'F minor',
  },
  {
    title: 'Sakura Rain',
    artist: 'yASu',
    genre: 'ピアノ',
    bpm: 72,
    duration: 195,
    price: 660,
    coverUrl: 'https://picsum.photos/seed/track3/400/400',
    previewUrl: '/audio/preview-3.mp3',
    fullUrl: '/audio/full-3.mp3',
    description: '桜と雨をイメージしたピアノソロ。感動的なシーンや映像作品のBGMとして幅広く使用可能。',
    tags: JSON.stringify(['ピアノ', '感動', '日本', '桜']),
    mood: 'Melancholic',
    musicKey: 'D major',
  },
  {
    title: 'Deep Forest',
    artist: 'yASu',
    genre: 'ネイチャー',
    bpm: 60,
    duration: 240,
    price: 550,
    coverUrl: 'https://picsum.photos/seed/track4/400/400',
    previewUrl: '/audio/preview-4.mp3',
    fullUrl: '/audio/full-4.mp3',
    description: '深い森の中をイメージした環境音楽。自然ドキュメンタリーや癒し系コンテンツに最適。',
    tags: JSON.stringify(['自然', '森', '癒し', 'ドキュメンタリー']),
    mood: 'Peaceful',
    musicKey: 'G major',
  },
  {
    title: 'Neon Dreams',
    artist: 'yASu',
    genre: 'シンセポップ',
    bpm: 110,
    duration: 225,
    price: 880,
    coverUrl: 'https://picsum.photos/seed/track5/400/400',
    previewUrl: '/audio/preview-5.mp3',
    fullUrl: '/audio/full-5.mp3',
    description: '80年代リバイバルを感じさせるレトロシンセポップ。レトロ系の映像やゲーム動画に。',
    tags: JSON.stringify(['レトロ', '80年代', 'シンセ', 'ポップ']),
    mood: 'Nostalgic',
    musicKey: 'A minor',
  },
  {
    title: 'Corporate Rise',
    artist: 'yASu',
    genre: 'ビジネスBGM',
    bpm: 95,
    duration: 160,
    price: 770,
    coverUrl: 'https://picsum.photos/seed/track6/400/400',
    previewUrl: '/audio/preview-6.mp3',
    fullUrl: '/audio/full-6.mp3',
    description: 'ビジネスプレゼンやコーポレート動画に最適な、洗練されたBGM。前向きでモチベーションが上がる曲調。',
    tags: JSON.stringify(['ビジネス', 'プレゼン', 'モチベーション', '企業']),
    mood: 'Motivational',
    musicKey: 'E major',
  },
  {
    title: 'Midnight Jazz',
    artist: 'yASu',
    genre: 'ジャズ',
    bpm: 88,
    duration: 205,
    price: 660,
    coverUrl: 'https://picsum.photos/seed/track7/400/400',
    previewUrl: '/audio/preview-7.mp3',
    fullUrl: '/audio/full-7.mp3',
    description: 'ムーディーな夜のジャズ。カフェBGMや夜のドライブ映像、グルメ動画のBGMにぴったり。',
    tags: JSON.stringify(['ジャズ', '夜', 'カフェ', 'ムーディー']),
    mood: 'Romantic',
    musicKey: 'Bb major',
  },
  {
    title: 'Summer Festival',
    artist: 'yASu',
    genre: 'ポップ',
    bpm: 132,
    duration: 190,
    price: 550,
    coverUrl: 'https://picsum.photos/seed/track8/400/400',
    previewUrl: '/audio/preview-8.mp3',
    fullUrl: '/audio/full-8.mp3',
    description: '夏祭りのような楽しい雰囲気のポップ曲。SNS動画やイベントのプロモーションに。',
    tags: JSON.stringify(['夏', '祭り', '楽しい', 'イベント']),
    mood: 'Happy',
    musicKey: 'C major',
  },
  {
    title: 'Epic Quest',
    artist: 'yASu',
    genre: 'オーケストラ',
    bpm: 120,
    duration: 270,
    price: 1100,
    coverUrl: 'https://picsum.photos/seed/track9/400/400',
    previewUrl: '/audio/preview-9.mp3',
    fullUrl: '/audio/full-9.mp3',
    description: '壮大なオーケストラ曲。ゲームやファンタジー映像、スポーツハイライトに最適。',
    tags: JSON.stringify(['オーケストラ', 'ゲーム', 'ファンタジー', '壮大']),
    mood: 'Epic',
    musicKey: 'D minor',
  },
  {
    title: 'Chill Lofi',
    artist: 'yASu',
    genre: 'Lo-Fi',
    bpm: 75,
    duration: 185,
    price: 440,
    coverUrl: 'https://picsum.photos/seed/track10/400/400',
    previewUrl: '/audio/preview-10.mp3',
    fullUrl: '/audio/full-10.mp3',
    description: 'リラックスできるLo-Fi HipHop。作業用BGMや勉強中のBGMとして人気。',
    tags: JSON.stringify(['Lo-Fi', 'HipHop', '作業用', '勉強']),
    mood: 'Chill',
    musicKey: 'F major',
  },
  {
    title: 'Tech Innovation',
    artist: 'yASu',
    genre: 'エレクトロニカ',
    bpm: 118,
    duration: 175,
    price: 770,
    coverUrl: 'https://picsum.photos/seed/track11/400/400',
    previewUrl: '/audio/preview-11.mp3',
    fullUrl: '/audio/full-11.mp3',
    description: 'テクノロジー・イノベーションをテーマにしたフューチャリスティックなサウンド。IT企業のプロモーション動画に。',
    tags: JSON.stringify(['テクノロジー', 'フューチャー', 'IT', 'イノベーション']),
    mood: 'Futuristic',
    musicKey: 'C# minor',
  },
  {
    title: 'Acoustic Afternoon',
    artist: 'yASu',
    genre: 'アコースティック',
    bpm: 85,
    duration: 200,
    price: 550,
    coverUrl: 'https://picsum.photos/seed/track12/400/400',
    previewUrl: '/audio/preview-12.mp3',
    fullUrl: '/audio/full-12.mp3',
    description: '暖かいアコースティックギターの音色。カフェや日常vlog、ライフスタイル系コンテンツに。',
    tags: JSON.stringify(['アコースティック', 'ギター', 'カフェ', 'Vlog']),
    mood: 'Warm',
    musicKey: 'G major',
  },
]

async function main() {
  console.log('🌱 シードデータを作成中...')

  for (const track of tracks) {
    await prisma.track.upsert({
      where: { id: track.title.toLowerCase().replace(/\s+/g, '-') },
      update: {},
      create: {
        id: track.title.toLowerCase().replace(/\s+/g, '-'),
        ...track,
      },
    })
  }

  const hashedPassword = await bcrypt.hash('demo1234', 10)
  await prisma.user.upsert({
    where: { email: 'demo@example.com' },
    update: {},
    create: {
      email: 'demo@example.com',
      password: hashedPassword,
      name: 'デモユーザー',
    },
  })

  console.log('✅ シードデータ作成完了！')
  console.log('デモアカウント: demo@example.com / demo1234')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
